### ISSUE TITLE
Record Screen + Video Query

### ISSUE THREAD

**Issue by utpal4job** [dhruv479/recorder#1]
Hello, How can i make "Record Screen + Video" simultaneously. 

Please help me to make that thing. Waiting for you reply.

Regards.

**Comment by dhruv479** [comment]
Hey @utpal4job, For this, you can take both streams, One from Screen Record and another from Camera and then use them as per your case,
You definitely don't want to merge them, but can use those data streams to be displayed in a player, save the stream to different blobs, or if you want to implement something advanced like, showing the video in the small portion of the screen recording, then you have to go a step further, merge those stream sources with the customization using libraries like ffmpeg and create new asset out of it.

**Comment by dhruv479** [comment]
I am closing this issue, if you need any further help, you can reach out to me on e-mail.
